### ISSUE TITLE
publicKeyToHex is not a function

### ISSUE THREAD

**Issue by Javamr123** [solana-labs/solana-solidity.js#12]
const address = publicKeyToHex(payer.publicKey);
                    ^

TypeError: publicKeyToHex is not a function

**Comment by Javamr123** [comment]
help!

**Comment by jordansexton** [comment]
I believe the issue is that the `@solana/solidity` npm package needs to be published again, there have been API changes the readme usage example depends on. cc @seanyoung

**Comment by seanyoung** [comment]
I've just published a new version: 0.0.17. It should be fixed in this.
