### ISSUE TITLE
Environment Compatibility Issue on Ubuntu 20.04 

### ISSUE THREAD

**Issue by gokulsan** [solana-labs/solana-solidity.js#14]
Hello Solana Devs,

I was trying to setup Solana Solidity JS tool on Ubuntu 20.04 version Linux environment. I am getting the following error while running the 'yarn docker' command. Could you please provide some guidance on the fix for this error.

yarn run v1.22.15
error @solana/solidity@0.0.17: The engine "node" is incompatible with this module. 
Expected version ">= 14". Got "10.19.0"
error Commands cannot run with an incompatible environment.

**Comment by seanyoung** [comment]
Your version of node is too old, unfortunately. The current node tls version is v14, and `@solana/solidity` requires that version.

Here are some steps to upgrade node on ubuntu 20.08 https://www.stewright.me/2021/03/install-nodejs-14-on-ubuntu-20-04/

**Comment by gokulsan** [comment]
Hi @seanyoung, 

It is strange. I had updated node version using NVM before running the commands. Please let me follow the recommended instructions and update this thread. Thank you so much for the quick response.

**Comment by seanyoung** [comment]
There are many ways to upgrade node. nvm should work fine. What were the steps you did to upgrade node using nvm and what is the output of `node --version` afterwards?

**Comment by jordansexton** [comment]
Closing this issue since upgrading Node on Ubuntu is out of scope for this library.
