### ISSUE TITLE
Call deployed contract

### ISSUE THREAD

**Issue by oznfc** [solana-labs/solana-solidity.js#16]
How can I call deployed contract with program and storage address ?

**Comment by oznfc** [comment]
when ı tried with react  I'm getting this error : 
``` Unhandled Rejection (TypeError): buf.writeBigUInt64LE is not a function ```

**Comment by seanyoung** [comment]
@oznfc how are you trying to use the npm library? I'm not following why this is happening, would you mind giving your exact steps for reproducing this error?

Also have you seen the steps in https://github.com/solana-labs/solana-solidity.js/blob/master/README.md ?

**Comment by jordansexton** [comment]
It sounds like Buffer is missing this method in your environment: https://nodejs.org/api/buffer.html#bufwritebiguint64levalue-offset

Node.js has this method going back quite a few versions. If you're running this with React, you'll need to add a polyfill for `Buffer` to your build setup.
