### ISSUE TITLE
Several transactions in depoyed erc20 program

### ISSUE THREAD

**Issue by jjordan-quantum** [solana-labs/solana-solidity.js#23]
I deployed the erc20 contract in the examples to devnet, and it turns out there are 30 transactions for the program upon deployment.
Was this required to set up the storage for the contract? 
Or maybe break the execution logic into several parts?
Any insight would be helpful.  Thanks!

https://explorer.solana.com/address/48iyexQULtnRnmUicqG6QJmwcHVeC8ap1xf6Y3Z91TSc?cluster=devnet

**Comment by seanyoung** [comment]
The largest part of this uploading the program code (the BPF so file). This is a one-time operation, which requires many transactions, and is also the most expensive part. Once the program is uploaded, transactions will be few, fast and not expensive.

**Comment by jjordan-quantum** [comment]
Gotcha. Thanks!
