### ISSUE TITLE
InvalidStorageAccountError

### ISSUE THREAD

**Issue by yuwiggin** [solana-labs/solana-solidity.js#31]
I tried to use solang to compile [an example: flipper.sol](https://solang.readthedocs.io/en/latest/examples.html) and [deploy it and test flipper.js](https://solang.readthedocs.io/en/latest/targets/solana.html) but failed:

> $ node flipper.js
> bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
> Connecting to your local Solana node ...
> Airdropping SOL to a new wallet ...
> Program deployment finished, deploying the flipper contract ...
> /home/xxx/solidity/node_modules/@solana/solidity/lib/contract.js:106
>                 throw new errors_1.InvalidStorageAccountError();
>                       ^
> 
> InvalidStorageAccountError
>     at Contract.<anonymous> (/home/xxx/solidity/node_modules/@solana/solidity/lib/contract.js:106:23)
>     at Generator.next (<anonymous>)
>     at /home/xxx/solidity/node_modules/@solana/solidity/lib/contract.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (/home/xxx/solidity/node_modules/@solana/solidity/lib/contract.js:4:12)
>     at Contract.deploy (/home/xxx/solidity/node_modules/@solana/solidity/lib/contract.js:104:16)
>     at /home/xxx/solidity/flipper.js:27:20
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

My env:

> Ubuntu20.04.4 on WSL2(windows11),
> Solana: 1.10.31
> @solana-solidity: 0.0.20
> solang: 0.1.12
> 

Any suggestion?

**Comment by seanyoung** [comment]
You are right, this example is broken. The fix is here: https://github.com/hyperledger-labs/solang/pull/941

The example in the readme is correct: https://github.com/hyperledger-labs/solang/blob/main/README.md
