### ISSUE TITLE
docs and source are out of sync

### ISSUE THREAD

**Issue by deian** [solana-labs/solana-solidity.js#35]
I'm not sure how extensive this is, but at lin one case the docs and source are out of sync:[`deploy()` in the docs still takes a program Signer](https://solana-labs.github.io/solana-solidity.js/classes/Contract.html#deploy) whereas [implementation](ttps://github.com/solana-labs/solana-solidity.js/blob/master/src/contract.ts#L177) no longer does.

**Comment by seanyoung** [comment]
Documentation updated https://github.com/solana-labs/solana-solidity.js/commit/8b12cb951c074a64fa3056658e8ebc33548ce2ea
